# Generated by Django 6.0.6 on 2026-09-06 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_deliverypartnerprofile_latitude_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliverypartnerprofile',
            old_name='latitude',
            new_name='current_latitude',
        ),
        migrations.RenameField(
            model_name='deliverypartnerprofile',
            old_name='longitude',
            new_name='current_longitude',
        ),
        migrations.AddField(
            model_name='deliverypartnerprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
