# Generated by Django 6.0.6 on 2026-07-13 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_stock_product_updated_at'),
        ('vendors', '0003_remove_vendor_address_remove_vendor_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='vendors.vendorprofile'),
        ),
    ]
