# Generated by Django 6.0.6 on 2026-08-11 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_veg',
            field=models.BooleanField(default=True),
        ),
    ]
