# Generated by Django 6.0.6 on 2026-07-13 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_vendor'),
        ('vendors', '0003_remove_vendor_address_remove_vendor_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vendor',
        ),
    ]
