# Generated by Django 6.0.6 on 2026-08-03 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0004_delete_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorprofile',
            name='description',
        ),
    ]
