# Generated by Django 6.0.6 on 2026-08-13 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0006_vendorprofile_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorprofile',
            name='closing_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='opening_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
