# Generated by Django 6.0.6 on 2026-08-14 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0007_alter_vendorprofile_closing_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorprofile',
            name='address',
        ),
    ]
