# Generated by Django 6.0.6 on 2026-08-21 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0008_remove_vendorprofile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='razorpay_account_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
