# Generated by Django 6.0.6 on 2026-09-02 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0009_vendorprofile_razorpay_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='food_type',
            field=models.CharField(choices=[('veg', 'Veg Only'), ('non_veg', 'Non-Veg Only'), ('both', 'Veg & Non-Veg')], default='both', max_length=10),
        ),
    ]
